const {
	MessageType
} = require("@adiwajshing/baileys");
const fs = require("fs-extra")
const { color, bgcolor } = require('./lib/color')
const { uncache, nocache } = require('./lib/loader')
module.exports = autoupdate = async (Ramdani, autoupdate) => {

require('./sc ori by Ramdani.java')
nocache('../sc ori by Ramdani.java', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./ramdani.js')
nocache('../ramdani.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./main.js')
nocache('../main.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./message/help.js')
nocache('../message/help.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./message/allmenu.js')
nocache('../message/allmenu.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./message/group.js')
nocache('../message/group.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./message/mess.js')
nocache('../message/mess.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/afk.js')
nocache('../lib/afk.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/asupan.js')
nocache('../lib/asupan.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/asupan2.js')
nocache('../lib/asupan2.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/atm.js')
nocache('../lib/atm.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/color.js')
nocache('../lib/color.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/exif.js')
nocache('../lib/exif.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/fetch.js')
nocache('../lib/fetch.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/game.js')
nocache('../lib/game.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/gameGelud.js')
nocache('../lib/gameGelud.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/gif.js')
nocache('../lib/gif.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/level.js')
nocache('../lib/level.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/limit.js')
nocache('../lib/limit.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/lirik.js')
nocache('../lib/lirik.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/loader.js')
nocache('../lib/loader.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/mediafire.js')
nocache('../lib/mediafire.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/misc.js')
nocache('../lib/misc.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/myfunc.js')
nocache('../lib/myfunc.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/otakudesu.js')
nocache('../lib/otakudesu.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/premium.js')
nocache('../lib/premium.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/scrapegame.js')
nocache('../lib/scrapegame.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/sewa.js')
nocache('../lib/sewa.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/simple.js')
nocache('../lib/simple.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/sticker.js')
nocache('../lib/sticker.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/totalcmd.js')
nocache('../lib/totalcmd.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/Toxic.js')
nocache('../lib/Toxic.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/uploadimage.js')
nocache('../lib/uploadimage.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/virtex.js')
nocache('../lib/virtex.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/y2mate.js')
nocache('../lib/y2mate.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./lib/ytdl.js')
nocache('../lib/ytdl.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/payment.js')
nocache('../plugins/payment.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/storemenu.js')
nocache('../plugins/storemenu.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topupfreefire.js')
nocache('../plugins/topupfreefire.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topupmobilelegends.js')
nocache('../plugins/topupmobilelegends.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topuppubg.js')
nocache('../plugins/topuppubg.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topuppointblank.js')
nocache('../plugins/topuppointblank.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topupgopay.js')
nocache('../plugins/topupgopay.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topupdana.js')
nocache('../plugins/topupdana.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topupovo.js')
nocache('../plugins/topupovo.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./plugins/topuppulsa.js')
nocache('../plugins/topuppulsa.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/vn.json')
nocache('../temp/vn.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/foto.json')
nocache('../temp/foto.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/image.json')
nocache('../temp/image.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/video.json')
nocache('../temp/video.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/stik.json')
nocache('../temp/stik.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./temp/stick.json')
nocache('../temp/stick.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/bot/scommand.json')
nocache('../database/bot/scommand.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/bot/limit.json')
nocache('../database/bot/limit.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/bot/totalcmd.json')
nocache('../database/bot/totalcmd.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/bot/update.json')
nocache('../database/bot/update.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/group/antilink.json')
nocache('../database/group/antilink.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/group/welcome.json')
nocache('../database/group/welcome.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/group/leveling.json')
nocache('../database/group/leveling.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/group/sewa.json')
nocache('../database/group/sewa.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/group/mute.json')
nocache('../database/group/mute.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/afk.json')
nocache('../database/user/afk.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/banned.json')
nocache('../database/user/banned.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/register.json')
nocache('../database/user/register.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/dewasa.json')
nocache('../database/user/dewasa.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/limit.json')
nocache('../database/user/limit.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/level.json')
nocache('../database/user/level.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/premium.json')
nocache('../database/user/premium.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/user/uang.json')
nocache('../database/user/uang.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/asahotak.json')
nocache('../database/asahotak.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/autorevoke.json')
nocache('../database/autorevoke.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/caklontong.json')
nocache('../database/caklontong.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/kuismath.json')
nocache('../database/kuismath.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/susunkata.json')
nocache('../database/susunkata.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakanime.json')
nocache('../database/tebakanime.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakkata.json')
nocache('../database/tebakkata.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakbendera.json')
nocache('../database/tebakbendera.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakgambar.json')
nocache('../database/tebakgambar.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakkimia.json')
nocache('../database/tebakkimia.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebakjenaka.json')
nocache('../database/tebakjenaka.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebaklagu.json')
nocache('../database/tebaklagu.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebaklirik.json')
nocache('../database/tebaklirik.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebaksiapaaku.json')
nocache('../database/tebaksiapaaku.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/tebaktebakan.json')
nocache('../database/tebaktebakan.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/totalcmd.json')
nocache('../database/totalcmd.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./database/userhit.json')
nocache('../database/userhit.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./config/setting.json')
nocache('../config/setting.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./config/gamesetting.json')
nocache('../config/gamesetting.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./config/apikey.json')
nocache('../config/apikey.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./config/fake.json')
nocache('../config/fake.json', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./api/api.js')
nocache('../api/api.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./api/apidanzz.js')
nocache('../api/apidanzz.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))
require('./api/apiramdani.js')
nocache('../api/apiramdani.js', module => console.log(color('[WARN]', 'yellow'), color(`'${module}'`, 'yellow'), 'File is updated!'))